# Generated by Django 5.1.7 on 2025-03-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
