# Generated by Django 5.1.7 on 2025-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_ram_alter_product_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='network',
            field=models.CharField(blank=True, default='4G', max_length=20),
        ),
    ]
