# Generated by Django 5.1.7 on 2025-04-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_product_battery_product_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.DecimalField(blank=True, decimal_places=0, default=4, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.DecimalField(blank=True, decimal_places=0, default=64, max_digits=3),
        ),
    ]
