# Generated by Django 5.1.7 on 2025-04-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_product_ram_alter_product_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.DecimalField(decimal_places=0, default=4, max_digits=3),
        ),
    ]
