# Generated by Django 5.1.7 on 2025-04-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_product_camera_product_display_alter_product_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, default='Snapdragon 8 Gen 3 Processor', max_length=20),
        ),
    ]
