# Generated by Django 5.1.7 on 2025-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_product_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.DecimalField(blank=True, decimal_places=0, default=64, max_digits=4),
        ),
    ]
