# Generated by Django 5.1.7 on 2025-04-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_product_ram_alter_product_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.AddField(
            model_name='product',
            name='ramm',
            field=models.CharField(blank=True, default='4 GB', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='storagee',
            field=models.CharField(blank=True, default='64 GB', max_length=20),
        ),
    ]
