# Generated by Django 5.1.7 on 2025-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_image2_product_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('original_price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('description', models.CharField(max_length=100)),
                ('detail_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, upload_to='images/')),
                ('is_sale', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='home.category')),
            ],
        ),
    ]
