# Generated by Django 5.1.7 on 2025-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
