# Generated by Django 5.1.7 on 2025-04-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_ram_product_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3),
        ),
    ]
