# Generated by Django 5.1.7 on 2025-04-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_product_ram_remove_product_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.DecimalField(blank=True, decimal_places=0, default=5000, max_digits=4),
        ),
    ]
