# Generated by Django 5.1.7 on 2025-04-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_product_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.CharField(blank=True, default='50MP + 10MP+ 2MP Camera', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(blank=True, default='6.8" Dynamic AMOLED 2X, 70HZ', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, default='Snapdragon 8 Gen 3 Processor', max_length=50),
        ),
    ]
